#include "../include/nan_cli_lib.h"

#include <cctype>
#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <sys/wait.h>
#include <unistd.h>

namespace fs = std::filesystem;

namespace nancli {

namespace {

std::string trim(const std::string& s) {
    size_t b = 0;
    while (b < s.size() && std::isspace(static_cast<unsigned char>(s[b]))) ++b;
    size_t e = s.size();
    while (e > b && std::isspace(static_cast<unsigned char>(s[e - 1]))) --e;
    return s.substr(b, e - b);
}

std::vector<std::string> split_ws(const std::string& s) {
    std::vector<std::string> out;
    std::istringstream iss(s);
    std::string tok;
    while (iss >> tok) out.push_back(tok);
    return out;
}

std::unordered_map<std::string, std::string> default_config() {
    return {
        {"lib_dir", "./lib"},
        {"cache_dir", "./.npi_cache"},
        {"registry_url", "https://registry.nanlang.org"},
        {"compiler", "./bin/nanlang_cpp"},
        {"build_flags", ""},
        {"output_dir", "./out"},
    };
}

std::string current_executable_path() {
    char buf[4096] = {};
    ssize_t n = ::readlink("/proc/self/exe", buf, sizeof(buf) - 1);
    if (n <= 0) return "";
    buf[n] = '\0';
    return std::string(buf);
}

std::string find_in_path(const std::string& bin_name) {
    const char* path_env = std::getenv("PATH");
    if (!path_env) return "";
    std::string path(path_env);
    std::stringstream ss(path);
    std::string item;
    while (std::getline(ss, item, ':')) {
        if (item.empty()) continue;
        fs::path candidate = fs::path(item) / bin_name;
        if (fs::exists(candidate)) return candidate.string();
    }
    return "";
}

int decode_wait_status(int status) {
    if (status == -1) return 127;
    if (WIFEXITED(status)) return WEXITSTATUS(status);
    return 1;
}

int run_shell(const std::string& cmdline) {
    return decode_wait_status(std::system(cmdline.c_str()));
}

void write_placeholder_output(const std::string& out_path, const std::string& manifest_path) {
    fs::create_directories(fs::path(out_path).parent_path());
    std::ofstream out(out_path, std::ios::binary);
    out << "# npi placeholder output\n"
        << "# Real nanlang binary would be here.\n"
        << "# Manifest: " << manifest_path << "\n";
}

void resolve_deps(const ReqFile& rf, const Config& cfg, bool dry_run) {
    if (!dry_run) {
        fs::create_directories(cfg.lib_dir);
        fs::create_directories(cfg.cache_dir);
        fs::create_directories(cfg.output_dir);
    }

    for (const auto& pkg : rf.packages) {
        fs::path pkg_dir = fs::path(cfg.lib_dir) / pkg.name;
        if (dry_run) {
            std::cout << "      [dry-run] would stage " << pkg.to_string()
                      << " -> " << pkg_dir.string() << "\n";
            continue;
        }

        fs::create_directories(pkg_dir);
        fs::path stub = pkg_dir / (pkg.name + ".nl");
        if (!fs::exists(stub)) {
            std::ofstream f(stub);
            f << "// Stub for " << pkg.to_string() << " (staged by npi)\n"
              << "// Replace with real source.\n"
              << "fn init() -> void {}\n";
        }
        std::cout << "      [OK] staged " << pkg.to_string() << "\n";
    }
}

void write_manifest(const std::string& path, const ReqFile& rf, const Config& cfg) {
    fs::create_directories(fs::path(path).parent_path());
    std::ofstream out(path, std::ios::binary);
    out << "# npi_manifest.conf — generated by npi, do not hand-edit\n";
    out << "lib_dir     = " << cfg.lib_dir << "\n";
    out << "output_dir  = " << cfg.output_dir << "\n";
    out << "build_flags = " << cfg.build_flags << "\n";
    out << "package_count = " << rf.count() << "\n\n";
    out << "[packages]\n";
    for (const auto& pkg : rf.packages) out << "  " << pkg.to_string() << "\n";
}

int invoke_compiler(const Config& cfg, const std::string& manifest, const std::string& out_path,
                    const BuildOptions& opts) {
    std::vector<std::string> args = {
        cfg.compiler,
        "build",
        "--manifest", manifest,
        "--output", out_path,
        "--lib", cfg.lib_dir,
    };
    if (!cfg.build_flags.empty()) {
        auto flags = split_ws(cfg.build_flags);
        args.insert(args.end(), flags.begin(), flags.end());
    }

    if (opts.dry_run) {
        std::ostringstream cmd;
        for (size_t i = 0; i < args.size(); ++i) {
            if (i) cmd << " ";
            cmd << shell_quote(args[i]);
        }
        std::cout << "      [dry-run] would run: " << cmd.str() << "\n";
        return 0;
    }

    int rc = run_command(args, opts.verbose);
    if (rc != 0) {
        std::cout << "[npi] [WARN] compiler not found or failed (exit=" << rc
                  << ") — writing placeholder output\n";
        write_placeholder_output(out_path, manifest);
    }
    return 0;
}

} // namespace

std::string full_banner() {
    return std::string(kProjectName) + " v" + kVersion + " — NanLang Unified Monorepo";
}

std::string PackageEntry::to_string() const {
    if (!version.empty()) return name + "@" + version;
    return name;
}

int ReqFile::count() const {
    return static_cast<int>(packages.size());
}

ReqFile parse_reqfile(const std::string& path) {
    std::ifstream in(path);
    if (!in.is_open()) {
        throw std::runtime_error("reqfile: cannot open \"" + path + "\"");
    }

    ReqFile rf;
    rf.path = path;
    std::string raw;
    int line_no = 0;

    while (std::getline(in, raw)) {
        ++line_no;
        std::string comment;
        size_t hash = raw.find('#');
        if (hash != std::string::npos) {
            comment = trim(raw.substr(hash + 1));
            raw = raw.substr(0, hash);
        }

        std::string line = trim(raw);
        if (line.empty()) continue;

        if (line.find(' ') != std::string::npos || line.find('\t') != std::string::npos) {
            throw std::runtime_error(
                "reqfile: line " + std::to_string(line_no) +
                ": unexpected whitespace in \"" + line + "\" (use name@version)"
            );
        }

        PackageEntry pkg;
        pkg.comment = comment;
        pkg.line = line_no;

        size_t at = line.find('@');
        if (at == std::string::npos) {
            pkg.name = trim(line);
        } else {
            pkg.name = trim(line.substr(0, at));
            pkg.version = trim(line.substr(at + 1));
            if (pkg.version.empty()) {
                throw std::runtime_error(
                    "reqfile: line " + std::to_string(line_no) +
                    ": empty version after '@' in \"" + line + "\""
                );
            }
        }

        if (pkg.name.empty()) {
            throw std::runtime_error("reqfile: line " + std::to_string(line_no) + ": empty package name");
        }

        rf.packages.push_back(pkg);
    }

    return rf;
}

std::string config_path() {
    const char* env = std::getenv("NPI_CONF");
    if (env && *env) return std::string(env);
    return "npi.conf";
}

Config load_config(const std::string& path) {
    Config cfg;
    cfg.raw = default_config();

    std::ifstream in(path);
    if (!in.is_open()) {
        if (fs::exists(path)) {
            throw std::runtime_error("config: cannot open \"" + path + "\"");
        }
    } else {
        std::string line;
        int line_no = 0;
        while (std::getline(in, line)) {
            ++line_no;
            std::string t = trim(line);
            if (t.empty() || t.rfind("#", 0) == 0) continue;
            size_t eq = t.find('=');
            if (eq == std::string::npos) {
                throw std::runtime_error(
                    "config: line " + std::to_string(line_no) + ": missing '=' in \"" + t + "\""
                );
            }
            std::string key = trim(t.substr(0, eq));
            std::string val = trim(t.substr(eq + 1));
            if (key.empty()) {
                throw std::runtime_error("config: line " + std::to_string(line_no) + ": empty key");
            }
            cfg.raw[key] = val;
        }
    }

    cfg.lib_dir = cfg.raw["lib_dir"];
    cfg.cache_dir = cfg.raw["cache_dir"];
    cfg.registry_url = cfg.raw["registry_url"];
    cfg.compiler = cfg.raw["compiler"];
    cfg.build_flags = cfg.raw["build_flags"];
    cfg.output_dir = cfg.raw["output_dir"];
    return cfg;
}

std::string Config::get(const std::string& key) const {
    auto it = raw.find(key);
    return it == raw.end() ? "" : it->second;
}

std::string Config::dump() const {
    std::ostringstream out;
    out << "npi.conf (resolved):\n";
    out << "  lib_dir      = " << lib_dir << "\n";
    out << "  cache_dir    = " << cache_dir << "\n";
    out << "  registry_url = " << registry_url << "\n";
    out << "  compiler     = " << compiler << "\n";
    out << "  build_flags  = " << build_flags << "\n";
    out << "  output_dir   = " << output_dir << "\n";
    return out.str();
}

BuildResult run_build(const BuildOptions& opts_in) {
    BuildOptions opts = opts_in;
    auto start = std::chrono::steady_clock::now();
    if (opts.req_path.empty()) throw std::runtime_error("build: missing req.txt path");
    if (opts.conf_path.empty()) opts.conf_path = config_path();

    std::cout << "[npi] Reading requirements: " << opts.req_path << "\n";
    ReqFile rf = parse_reqfile(opts.req_path);
    std::cout << "[npi] Found " << rf.count() << " package(s)\n";
    for (const auto& pkg : rf.packages) {
        std::cout << "      * " << pkg.to_string() << "\n";
    }

    std::cout << "[npi] Loading config: " << opts.conf_path << "\n";
    Config cfg = load_config(opts.conf_path);
    if (opts.verbose) std::cout << cfg.dump();

    std::cout << "[npi] Resolving dependencies into: " << cfg.lib_dir << "\n";
    resolve_deps(rf, cfg, opts.dry_run);

    fs::path manifest_path = fs::path(cfg.output_dir) / "npi_manifest.conf";
    std::cout << "[npi] Writing manifest: " << manifest_path.string() << "\n";
    if (!opts.dry_run) {
        write_manifest(manifest_path.string(), rf, cfg);
    }

    std::string target = opts.target_name.empty() ? "output.elf" : opts.target_name;
    fs::path out_path = fs::path(cfg.output_dir) / target;
    std::cout << "[npi] Invoking compiler: " << cfg.compiler << " build\n";
    invoke_compiler(cfg, manifest_path.string(), out_path.string(), opts);

    auto end = std::chrono::steady_clock::now();
    double seconds = std::chrono::duration<double>(end - start).count();
    std::cout << "[npi] [OK] Build complete: " << out_path.string() << " (" << seconds << "s)\n";

    BuildResult result;
    result.output_file = out_path.string();
    result.duration_seconds = seconds;
    result.packages = rf.count();
    return result;
}

std::string shell_quote(const std::string& in) {
    std::string out = "'";
    for (char c : in) {
        if (c == '\'') out += "'\"'\"'";
        else out.push_back(c);
    }
    out.push_back('\'');
    return out;
}

int run_command(const std::vector<std::string>& args, bool inherit_io) {
    std::ostringstream cmd;
    for (size_t i = 0; i < args.size(); ++i) {
        if (i) cmd << " ";
        cmd << shell_quote(args[i]);
    }
    if (!inherit_io) cmd << " >/dev/null 2>/dev/null";
    return run_shell(cmd.str());
}

std::string resolve_cpp_command_path() {
    if (const char* env = std::getenv("NANLANG_CPP")) {
        if (*env && fs::exists(env)) return std::string(env);
    }

    std::string exe = current_executable_path();
    if (!exe.empty()) {
        fs::path candidate = fs::path(exe).parent_path() / "nanlang_cpp";
        if (fs::exists(candidate)) return candidate.string();
    }

    std::string in_path = find_in_path("nanlang_cpp");
    if (!in_path.empty()) return in_path;

    if (fs::exists("./bin/nanlang_cpp")) return "./bin/nanlang_cpp";
    throw std::runtime_error(
        "could not find nanlang_cpp (tried NANLANG_CPP, executable dir, PATH, and ./bin)"
    );
}

std::string resolve_preprocessor_path() {
    if (const char* env = std::getenv("NANLANG_PREPROCESSOR")) {
        if (*env && fs::exists(env)) return std::string(env);
    }

    std::string exe = current_executable_path();
    if (!exe.empty()) {
        fs::path exe_dir = fs::path(exe).parent_path();
        std::vector<fs::path> candidates = {
            exe_dir / ".." / "share" / "nanlang" / "scripts" / "nan_preprocessor.raku",
            exe_dir / "scripts" / "nan_preprocessor.raku",
            exe_dir / ".." / "scripts" / "nan_preprocessor.raku",
        };
        for (const auto& p : candidates) {
            if (fs::exists(p)) return p.lexically_normal().string();
        }
    }

    if (fs::exists("./scripts/nan_preprocessor.raku")) return "./scripts/nan_preprocessor.raku";
    if (fs::exists("/usr/share/nanlang/scripts/nan_preprocessor.raku")) {
        return "/usr/share/nanlang/scripts/nan_preprocessor.raku";
    }

    std::string in_path = find_in_path("nan_preprocessor.raku");
    if (!in_path.empty()) return in_path;

    throw std::runtime_error(
        "could not find nan_preprocessor.raku (tried NANLANG_PREPROCESSOR, executable-relative paths, PATH, and /usr/share)"
    );
}

std::string resolve_raku_path() {
    std::string in_path = find_in_path("raku");
    if (!in_path.empty()) return in_path;
    throw std::runtime_error("raku executable not found in PATH (required for preprocessing)");
}

void preprocess_source_file(const std::string& source_path, const std::string& out_path) {
    std::string raku = resolve_raku_path();
    std::string pre = resolve_preprocessor_path();

    std::ostringstream cmd;
    cmd << shell_quote(raku) << " "
        << shell_quote(pre) << " "
        << shell_quote(source_path) << " > "
        << shell_quote(out_path);

    int rc = run_shell(cmd.str());
    if (rc != 0) {
        throw std::runtime_error("preprocess failed for " + source_path + ": exit status " + std::to_string(rc));
    }
}

} // namespace nancli
